// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl0EOKdEJq4WujEE5YKI_-L1n2rtMsux0',
    appId: '1:161712957511:web:6d96eceb0a792eabf32962',
    messagingSenderId: '161712957511',
    projectId: 'chat-app-85e36',
    authDomain: 'chat-app-85e36.firebaseapp.com',
    storageBucket: 'chat-app-85e36.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv2GOU2RAyiwZ1mW_66YxIQ6EER5GBj84',
    appId: '1:161712957511:android:8561563a947726b4f32962',
    messagingSenderId: '161712957511',
    projectId: 'chat-app-85e36',
    storageBucket: 'chat-app-85e36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk2hYKBK_hQ-MbFpfdNMzwuWPyGXJc2Ds',
    appId: '1:161712957511:ios:3b620d5fb599dca4f32962',
    messagingSenderId: '161712957511',
    projectId: 'chat-app-85e36',
    storageBucket: 'chat-app-85e36.firebasestorage.app',
    iosBundleId: 'com.example.appChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk2hYKBK_hQ-MbFpfdNMzwuWPyGXJc2Ds',
    appId: '1:161712957511:ios:3b620d5fb599dca4f32962',
    messagingSenderId: '161712957511',
    projectId: 'chat-app-85e36',
    storageBucket: 'chat-app-85e36.firebasestorage.app',
    iosBundleId: 'com.example.appChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl0EOKdEJq4WujEE5YKI_-L1n2rtMsux0',
    appId: '1:161712957511:web:c82fb716b0c34042f32962',
    messagingSenderId: '161712957511',
    projectId: 'chat-app-85e36',
    authDomain: 'chat-app-85e36.firebaseapp.com',
    storageBucket: 'chat-app-85e36.firebasestorage.app',
  );
}
